name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write    
    
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: qemu-w64-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        shell: cmd
        run: |
          curl https://qemu.weilnetz.de/w64/2021/qemu-w64-setup-${{ github.ref_name }}.exe -L -O
          
      - name: innoextract 
        shell: cmd
        run: |
          qemu-w64-setup-${{ github.ref_name }}.exe /S /D=%CD%\installation &&^
          cd installation &&^
          del qemu-uninstall.exe
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "installation"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "installation/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
